### ISSUE TITLE
How NOT to upload source code

### ISSUE THREAD

**Issue by Archetipo95** [shogo82148/actions-upload-release-asset#164]
Is it possibile to have an option where I can select not to upload source code (zip and tar.gz) ?
Or maybe there is already an easier way ?

**Comment by shogo82148** [comment]
actions-upload-release-asset  uses [@actions/glob](https://github.com/actions/toolkit/tree/master/packages/glob), and it has Exclude patterns https://github.com/actions/toolkit/tree/master/packages/glob#exclude-patterns
so `asset_path` can accept the following pattern.

```
**
!*.zip
!*.tar.gz
```

**Comment by Archetipo95** [comment]
Am I doing something wrong here or?
![image](https://user-images.githubusercontent.com/11798239/102710592-91f0f900-42b3-11eb-92f6-827c97572892.png)
![image](https://user-images.githubusercontent.com/11798239/102710596-9b7a6100-42b3-11eb-8c04-a217c0bb2b58.png)

**Comment by shogo82148** [comment]
you mean "Source code (zip)" and "Source code (tar.gz)"?
hmm, I don't know how to remove them. All releases I've seen on GitHub have the links for their source code.
